const API="https://verifyai-gqc9.onrender.com";
const $=id=>document.getElementById(id);
const aiText=$("aiText"),codeText=$("codeText"),language=$("language"),infoPanel=$("infoPanel"),codePanel=$("codePanel"),documentPanel=$("documentPanel"),results=$("results"),codeResults=$("codeResults"),urlText=$("urlText"),urlPanel=$("urlPanel"),loginScreen=$("loginScreen"),app=$("app");
let currentMode="information", GOOGLE_CLIENT_ID="";
function showApp(user){localStorage.setItem("verifyAIUser",JSON.stringify(user));loginScreen.classList.add("hidden");app.classList.remove("hidden");updateUserUI(user)}
function updateUserUI(user){const n=user?.name||"Google User",e=user?.email||"";$('userName').textContent=n;$('userEmail').textContent=e;$('userAvatar').textContent=n[0].toUpperCase();$('settingsAccountName').textContent=n;$('settingsAccountText').textContent=e?`Signed in as ${e}.`:"Signed in with Google."}
async function postJSON(url,body){const r=await fetch(API+url,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const d=await r.json();if(!r.ok||d.error)throw new Error(d.detail||d.error||"Request failed.");return d}
async function handleGoogleCredential(r){try{const d=await postJSON("/auth/google",{credential:r.credential});showApp(d.user)}catch(e){alert("Google sign-in failed: "+e.message)}}
async function initializeGoogleSignIn(){try{const r=await fetch(API+"/config");const d=await r.json();GOOGLE_CLIENT_ID=d.google_client_id||""}catch(e){}if(!GOOGLE_CLIENT_ID||!window.google?.accounts?.id)return;google.accounts.id.initialize({client_id:GOOGLE_CLIENT_ID,callback:handleGoogleCredential,use_fedcm_for_button:true});google.accounts.id.renderButton($('googleLoginBtn'),{theme:"outline",size:"large",text:"continue_with",shape:"rectangular",width:320})}
const savedUser=JSON.parse(localStorage.getItem("verifyAIUser")||"null");if(savedUser)showApp(savedUser);window.addEventListener("load",initializeGoogleSignIn);
$('logoutBtn').onclick=()=>{if(window.google?.accounts?.id)google.accounts.id.disableAutoSelect();localStorage.removeItem("verifyAIUser");app.classList.add("hidden");loginScreen.classList.remove("hidden");initializeGoogleSignIn()};
function setMode(mode){currentMode=mode;document.querySelectorAll(".mode-btn").forEach(b=>b.classList.toggle("active",b.dataset.mode===mode));codePanel.classList.toggle("hidden",mode!=="code");documentPanel.classList.toggle("hidden",mode!=="document");infoPanel.classList.toggle("hidden",mode==="code"||mode==="document");urlPanel.classList.toggle("hidden",mode!=="url");results.classList.add("hidden");codeResults.classList.add("hidden");const labels={information:"Paste AI-generated information to verify",news:"Enter a news headline/topic or paste a news article",statistics:"Paste statistics or data claims",research:"Paste research text or citations",url:"Paste content or use the webpage URL below"};$('contentLabel').textContent=labels[mode]||"Paste content to verify";$('verifyBtn').textContent=mode==="url"?"🔗 Verify Webpage":mode==="news"?"📰 Verify Live News":"🔍 Verify Content";if(mode==="news")aiText.placeholder="Example: NASA announces a new Mars mission in 2030"}
document.querySelectorAll(".mode-btn").forEach(b=>b.onclick=()=>setMode(b.dataset.mode));
function showSection(s){["home","history","settings"].forEach(n=>$(n+"Section").classList.toggle("hidden",n!==s));document.querySelectorAll(".nav-item").forEach(b=>b.classList.toggle("active",b.dataset.section===s));if(s==="history")displayHistory()}
document.querySelectorAll(".nav-item").forEach(b=>b.onclick=()=>showSection(b.dataset.section));
$('newConversationBtn').onclick=()=>{aiText.value="";codeText.value="";urlText.value="";$('pdfFile').value="";results.classList.add("hidden");codeResults.classList.add("hidden");setMode("information");showSection("home");aiText.focus()};$('mobileMenuBtn').onclick=()=>document.querySelector(".sidebar").classList.toggle("mobile-open");$('clearHistoryBtn').onclick=clearHistory;$('settingsClearBtn').onclick=clearHistory;
function clearHistory(){localStorage.removeItem("verifyAIHistory");displayHistory()}
function progress(on){const box=$('loading');box.classList.toggle("hidden",!on);if(on){$('progressFill').style.width="12%";[1,2,3,4].forEach(n=>$('step'+n).classList.remove("active"));$('step1').classList.add("active");setTimeout(()=>{$('progressFill').style.width="35%";$('step2').classList.add("active")},450);setTimeout(()=>{$('progressFill').style.width="70%";$('step3').classList.add("active")},1000);setTimeout(()=>{$('progressFill').style.width="92%";$('step4').classList.add("active")},1700)}}
async function verifyContent(){const text=aiText.value.trim();if(currentMode!=="url"&&!text)throw new Error("Please enter content first.");if(currentMode==="url"){const u=urlText.value.trim();if(!u)throw new Error("Please enter a webpage URL.");return postJSON("/verify-url",{url:u,mode:"url"})}if(currentMode==="news")return postJSON("/verify-news-live",{query:text});return postJSON("/verify-content",{text,mode:currentMode})}
$('verifyBtn').onclick=async()=>{const btn=$('verifyBtn');btn.disabled=true;results.classList.add("hidden");progress(true);try{const d=await verifyContent();$('progressFill').style.width="100%";displayResults(d)}catch(e){alert("Something went wrong: "+e.message)}finally{setTimeout(()=>progress(false),250);btn.disabled=false}};
$('verifyPdfBtn').onclick=async()=>{const f=$('pdfFile').files[0];if(!f)return alert("Please select a PDF first.");const btn=$('verifyPdfBtn'),load=$('pdfLoading');btn.disabled=true;load.classList.remove("hidden");results.classList.add("hidden");try{const fd=new FormData();fd.append("file",f);const r=await fetch(API+"/verify-pdf",{method:"POST",body:fd});const d=await r.json();if(!r.ok)throw new Error(d.detail||"PDF verification failed.");displayResults(d)}catch(e){alert(e.message)}finally{btn.disabled=false;load.classList.add("hidden")}};
$('verifyCodeBtn').onclick=async()=>{const code=codeText.value.trim();if(!code)return alert("Please paste some code first.");const b=$('verifyCodeBtn'),l=$('codeLoading');b.disabled=true;l.classList.remove("hidden");try{displayCodeResults(await postJSON("/verify-code",{code,language:language.value}))}catch(e){alert(e.message)}finally{b.disabled=false;l.classList.add("hidden")}};
function displayResults(d){results.classList.remove("hidden");const claims=d.claims||[],score=Number(d.overall_score??0),counts={Supported:0,"Partially Supported":0,Contradicted:0,"Cannot Verify":0};claims.forEach(x=>counts[x.status]=(counts[x.status]||0)+1);$('score').textContent=score+"/100";$('summary').textContent=d.summary||"Analysis completed.";$('supportedCount').textContent=counts.Supported||0;$('partialCount').textContent=counts["Partially Supported"]||0;$('contradictedCount').textContent=counts.Contradicted||0;$('cannotCount').textContent=counts["Cannot Verify"]||0;$('claimCountBadge').textContent=claims.length+" claim"+(claims.length===1?"":"s");$('verifiedFraction').textContent=(counts.Supported||0)+"/"+claims.length;$('segSupported').style.width=(claims.length?counts.Supported/claims.length*100:0)+"%";$('segPartial').style.width=(claims.length?counts["Partially Supported"]/claims.length*100:0)+"%";$('segContradicted').style.width=(claims.length?counts.Contradicted/claims.length*100:0)+"%";$('segCannot').style.width=(claims.length?counts["Cannot Verify"]/claims.length*100:0)+"%";$('analyticsMessage').textContent=`${counts.Supported||0} of ${claims.length} claims verified by evidence • ${counts.Contradicted||0} contradicted.`;$('score').parentElement.parentElement.style.setProperty("--score",score);saveToHistory(d.source_url||d.filename||aiText.value.trim(),score,currentMode);const c=$('claims');c.innerHTML="";claims.forEach((x,i)=>{const card=document.createElement("div");card.className="claim-card";const ev=(x.evidence||[]).map(s=>`<div class="evidence-card"><div class="evidence-title">${escapeHTML(s.title||"Web Source")}</div><div class="evidence-content">${escapeHTML(s.content||"No evidence description available.")}</div>${s.url?`<a class="evidence-link" href="${escapeAttribute(s.url)}" target="_blank" rel="noopener noreferrer">🔗 View Source ↗</a>`:""}</div>`).join("");card.innerHTML=`<div class="claim-header"><h3>Claim ${i+1}</h3><span class="status ${getStatusClass(x.status)}">${getStatusIcon(x.status)} ${escapeHTML(x.status)}</span></div><div class="claim-section"><p class="section-label">CLAIM</p><p>${escapeHTML(x.claim)}</p></div><div class="claim-section"><p class="section-label">CONFIDENCE</p><div class="confidence-bar"><div class="confidence-fill" style="width:${Number(x.confidence||0)}%"></div></div><p class="confidence-text">${Number(x.confidence||0)}/100</p></div><div class="claim-section"><p class="section-label">AI EXPLANATION</p><p>${escapeHTML(x.explanation||"No explanation available.")}</p></div><div class="claim-section"><p class="section-label">WEB EVIDENCE</p>${ev||'<div class="evidence-card"><div class="evidence-content">⚠ No web evidence was found.</div></div>'}</div>`;c.appendChild(card)});window.scrollTo({top:0,behavior:"smooth"})}
function displayCodeResults(d){codeResults.classList.remove("hidden");$('codeScore').textContent=(d.score??0)+"/100";$('codeSummary').textContent=d.summary||"Code analysis completed.";const s=$('codeStatus');s.textContent=d.status||"Cannot Analyze";s.className="code-status "+(d.status==="Correct"?"code-good":d.status==="Issues Found"?"code-bad":"code-neutral");const i=$('codeIssues');i.innerHTML="";(d.issues||[]).forEach(x=>{const p=document.createElement("p");p.className="issue-item";p.textContent="⚠ "+x;i.appendChild(p)});if(!i.innerHTML)i.innerHTML='<p class="no-issue">✓ No major issues detected.</p>';$('correctedCode').textContent=d.corrected_code||codeText.value;saveToHistory(codeText.value.trim(),d.score,"Code")}
function getStatusClass(s){return s==="Supported"?"supported":s==="Partially Supported"?"partial":s==="Contradicted"?"contradicted":"cannot"}function getStatusIcon(s){return s==="Supported"?"✓":s==="Partially Supported"?"⚠":s==="Contradicted"?"✕":"?"}function escapeHTML(t){const d=document.createElement("div");d.textContent=t??"";return d.innerHTML}function escapeAttribute(t){return String(t??"").replace(/&/g,"&amp;").replace(/"/g,"&quot;").replace(/</g,"&lt;").replace(/>/g,"&gt;")}
function saveToHistory(text,score,type){let h=JSON.parse(localStorage.getItem("verifyAIHistory"))||[];h.unshift({text,score:score??0,type,time:new Date().toLocaleString()});if(h.length>20)h.pop();localStorage.setItem("verifyAIHistory",JSON.stringify(h))}
function displayHistory(){const l=$('historyList'),h=JSON.parse(localStorage.getItem("verifyAIHistory"))||[];if(!h.length){$('historyStats').innerHTML="";l.innerHTML='<p class="empty-history">No verification history yet.</p>';return}const avg=Math.round(h.reduce((a,x)=>a+Number(x.score||0),0)/h.length),best=Math.max(...h.map(x=>Number(x.score||0)));$('historyStats').innerHTML=`<div class="history-stat"><strong>CHECKS</strong><b>${h.length}</b></div><div class="history-stat"><strong>AVERAGE SCORE</strong><b>${avg}</b></div><div class="history-stat"><strong>BEST SCORE</strong><b>${best}</b></div><div class="history-stat"><strong>TOP MODE</strong><b>${escapeHTML(h.reduce((a,x)=>(a[x.type]=(a[x.type]||0)+1,a),{})&&Object.entries(h.reduce((a,x)=>(a[x.type]=(a[x.type]||0)+1,a),{})).sort((a,b)=>b[1]-a[1])[0]?.[0]||"—")}</b></div>`;l.innerHTML=h.map((x,i)=>`<div class="history-item" onclick="restoreHistory(${i})"><div class="history-type">${escapeHTML(x.type||"Information")}</div><div class="history-text">${escapeHTML((x.text||"").substring(0,180))}${(x.text||"").length>180?"...":""}</div><div class="history-meta"><span>Reliability Score: ${x.score}/100</span><small>${escapeHTML(x.time)}</small></div></div>`).join("")}
function restoreHistory(i){const h=JSON.parse(localStorage.getItem("verifyAIHistory"))||[],x=h[i];if(!x)return;showSection("home");if(x.type==="Code"){setMode("code");codeText.value=x.text}else{setMode(x.type||"information");aiText.value=x.text}window.scrollTo({top:0,behavior:"smooth"})}
$('demoBtn').onclick=()=>{setMode("information");aiText.value="The capital of Australia is Sydney.\nThe Earth revolves around the Sun.\nWater boils at 100°C at sea level.";aiText.focus()};
$('printReportBtn').onclick=()=>window.print();$('printResultsBtn').onclick=()=>window.print();
$('historySection').addEventListener("click",e=>{if(e.target.closest(".history-item"))document.querySelector(".sidebar")?.classList.remove("mobile-open")});
displayHistory();
